-- the password hash is generated by BCrypt Calculator Generator(https://www.dailycred.com/article/bcrypt-calculator)
INSERT INTO USERS (id, username, password, first_name, last_name, email, phone_number, enabled, last_password_reset_date) VALUES (1, 'user', '$2a$04$Vbug2lwwJGrvUXTj6z7ff.97IzVBkrJ1XfApfGNl.Z695zqcnPYra', 'Mariana', 'Lozano', 'user@example.com', '+1234567890', true, '2017-10-01 21:58:58.508-07');
INSERT INTO USERS (id, username, password, first_name, last_name, email, phone_number, enabled, last_password_reset_date) VALUES (2, 'admin', '$2a$04$Vbug2lwwJGrvUXTj6z7ff.97IzVBkrJ1XfApfGNl.Z695zqcnPYra', 'Santiago', 'Linares', 'admin@example.com', '+0987654321', true, '2017-10-01 18:57:58.508-07');
\

INSERT INTO AUTHORITY (id, name) VALUES (1, 'ROLE_USER');
INSERT INTO AUTHORITY (id, name) VALUES (2, 'ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (user_id, authority_id) VALUES (1, 1);
INSERT INTO USER_AUTHORITY (user_id, authority_id) VALUES (2, 1);
INSERT INTO USER_AUTHORITY (user_id, authority_id) VALUES (2, 2);

INSERT INTO PRODUCTOS (id, tipo) VALUES (1, 'tarjetaCredito');
INSERT INTO PRODUCTOS (id, tipo) VALUES (2, 'tarjetaDebito');


INSERT INTO SOLICITUDES (id, tipo, fecha) VALUES (2, 'Solicitud para tarjetaDebito', '2018-10-02 12:34:56.789-07');
INSERT INTO SOLICITUDES (id, tipo, fecha) VALUES (3, 'Solicitud para tarjetaDebito', '2018-11-15 09:21:45.123-07');
INSERT INTO SOLICITUDES (id, tipo, fecha) VALUES (4, 'Solicitud para tarjetaDebito', '2018-12-24 14:55:33.654-07');
INSERT INTO SOLICITUDES (id, tipo, fecha) VALUES (5, 'Solicitud para tarjetaDebito', '2019-01-03 18:20:11.567-07');
INSERT INTO SOLICITUDES (id, tipo, fecha) VALUES (6, 'Solicitud para tarjetaDebito', '2019-02-10 08:45:22.890-07');
INSERT INTO SOLICITUDES (id, tipo, fecha) VALUES (7, 'Solicitud para tarjetaDebito', '2019-03-22 23:12:34.321-07');
INSERT INTO SOLICITUDES (id, tipo, fecha) VALUES (8, 'Solicitud para tarjetaDebito', '2019-04-18 15:30:44.210-07');
INSERT INTO SOLICITUDES (id, tipo, fecha) VALUES (9, 'Solicitud para tarjetaDebito', '2019-05-27 19:07:56.123-07');
INSERT INTO SOLICITUDES (id, tipo, fecha) VALUES (10, 'Solicitud para tarjetaDebito', '2019-06-14 10:25:11.789-07');
INSERT INTO SOLICITUDES (id, tipo, fecha) VALUES (11, 'Solicitud para tarjetaDebito', '2019-07-05 22:58:22.456-07');
INSERT INTO SOLICITUDES (id, tipo, fecha) VALUES (12, 'Solicitud para tarjetaDebito', '2019-08-16 07:32:14.321-07');
INSERT INTO SOLICITUDES (id, tipo, fecha) VALUES (13, 'Solicitud para tarjetaDebito', '2019-09-09 20:45:33.654-07');
INSERT INTO SOLICITUDES (id, tipo, fecha) VALUES (14, 'Solicitud para tarjetaDebito', '2019-10-30 12:50:55.123-07');
INSERT INTO SOLICITUDES (id, tipo, fecha) VALUES (15, 'Solicitud para tarjetaDebito', '2019-11-25 14:15:44.210-07');
INSERT INTO SOLICITUDES (id, tipo, fecha) VALUES (16, 'Solicitud para tarjetaDebito', '2019-12-31 09:40:22.567-07');
INSERT INTO SOLICITUDES (id, tipo, fecha) VALUES (17, 'Solicitud para tarjetaDebito', '2020-01-20 18:23:33.890-07');
